---
title : "Experiment 3"
author: "Karoline Bading & Marius Barth"
date  : "`r Sys.Date()`"
abstract: |
  Beware, this is a test script!
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    code_folding: hide
  papaja::apa6_pdf:
    classoption: doc
editor_options: 
  chunk_output_type: console
---



```{r setup, include = FALSE}
library(afex)
library(emmeans)
library(ggeffects)
library(papaja)
library(memoise)
library(HMMTreeC)
library(TreeBUGS)
library(lavaan)

project_root <- rprojroot::find_rstudio_root_file()
study_folder <- file.path(project_root, "studies", "wsw3-joint-analysis")

set_sum_contrasts()

knitr::opts_chunk$set(
  echo = TRUE
  , message = FALSE
)
knitr::opts_knit$set(
  global.par = TRUE
)

source(file.path(project_root, "R", "mptinr_helper.R"))

file_cache <- cache_filesystem(path = file.path(project_root, ".rcache"), compress = "gzip", algo = "md5")
simpleMPT <- memoise(TreeBUGS::simpleMPT, cache = file_cache)
BayesFactorMPT <- memoise(TreeBUGS::BayesFactorMPT, cache = file_cache)
```

```{r global-par}
wesanderson::wes_palette("Zissou1", n = 3, type = "continuous") |>
  palette()
par(las = 1, cex = 1.2)
```


```{r exp3-read-data}
data_list <- readRDS(file.path(study_folder, "data", "data.rds"))
rating <- data_list$rating
mpt_data <- data_list$mpt_data
```


## Latent-trait MPT model

```{r}
model <- readRDS(file.path(study_folder, "model-objects", "trait-mpt.rds"))
summary(model)

model$mptInfo
```

## Mediation analysis

```{r}
individual_parameters <- as.data.frame(getParam(model, parameter = "theta"))
# individual_parameters$sid <- rownames(individual_parameters)

tt <- transformedParameters(model,
  list("p_us_identity = D*C", "p_us_valence = D*(1-C)*d", "p_us_id_or_val = D*(C + (1-C)*d)"),
  level = "individual"
) |>
  do.call(what = "rbind") |>
  colMeans()

branch_probabilities <- data.frame(
  p_us_valence = tt[grepl(names(tt), pattern = "p_us_valence")]
  , p_us_identity = tt[grepl(names(tt), pattern = "p_us_identity")]
  , p_us_id_or_val = tt[grepl(names(tt), pattern = "p_us_id_or_val")]
  , row.names = NULL
)

data <- cbind(data_list$mpt_data_hierarchical, individual_parameters, branch_probabilities)
```


```{r}
z <- function(x) {as.numeric(scale(x))}

data <- within(data, {
  Dd <- z(D) * z(d)
  DC <- z(D) * z(C)
  dC <- z(d) * z(C)
  DdC <- z(D) * z(d) * z(C)
})


mediation_syntax <-"
    # Regressions
    D ~ a_D*task_focus 
    C ~ a_C*task_focus
    d ~ a_d*task_focus
    # b ~ a_b*task_focus
    # a ~ a_a*task_focus
    Dd ~ a_Dd*task_focus
    DC ~ a_DC*task_focus
    dC ~ a_dC*task_focus
    DdC ~ a_DdC*task_focus
    # ec_effect ~ b_D*D + b_C*C + b_d*d + b_b*b + b_a*a + b_Dd*Dd + b_DC*DC + b_dC*dC + b_DdC*DdC + ade*task_focus
    ec_effect ~ b_D*D + b_C*C + b_d*d + b_Dd*Dd + b_DC*DC + b_dC*dC + b_DdC*DdC + ade*task_focus
    
    #Define New Parameters
    ab_D := a_D*b_D                                   #the product term is computed as a*b
    ab_C := a_C*b_C
    ab_d := a_d*b_d
    ab_Dd := a_Dd*b_Dd
    ab_DC := a_DC*b_DC
    ab_dC := a_dC*b_dC
    ab_DdC := a_DdC*b_DdC
    total_effect := ade + ab_D + ab_C + ab_d + ab_Dd + ab_DC + ab_dC + ab_DdC  #having defined ab, we can use this here.
"

sem(mediation_syntax, data = data) |>
  summary(standardized=TRUE)
```

```{r}
ec_lm <- lm(formula = ec_effect ~ D * C * d, data = data)
summary(ec_lm)
ec_lm |>
  marginaleffects::plot_predictions(condition = c("d", "C"))

ec_lm |>
  marginaleffects::plot_predictions(condition = c("C", "d"))

emtrends(ec_lm, var = "d", specs = ~ C, at = list(C = c(0, .1, .2, .3, .8))) |>
  summary(infer = TRUE)

emtrends(ec_lm, var = "C", specs = ~ d, at = list(d = ppoints(n = 10))) |>
  summary(infer = TRUE)
```

```{r three-way-interaction}
ec_lm |>
  marginaleffects::plot_predictions(condition = c("d", "C", "D"))

conditions <- list(
  d = seq(0, 1, length.out = 1e3)
  , C   = c(.2, .5, .8)
  , D = c(.2, .5, .8)
)

marginaleffects::plot_predictions(ec_lm, condition = conditions)
emtrends(ec_lm, var = "d", specs = ~ C + D, at = conditions[2:3]) |>
  summary(infer = TRUE)

```

```{r}
par(mfrow = c(1, 3))
plot(d ~ C, data = data, pch = 16)
abline(a = 0, b = 1)
plot(d ~ D, data = data, pch = 16)
plot(C ~ D, data = data, pch = 16)
```

- 



### with unconditional probabilities of US-valence or US-identity memory as predictors

```{r}
# hist(data$p_us_identity)
# hist(data$p_us_valence)
data$ln_us_identity <- (data$p_us_identity)
data$ln_us_valence <- (data$p_us_valence)
data$ln_us_id_or_val <- (data$p_us_id_or_val)

data$I_valence_memory <- data$ln_us_identity * data$ln_us_valence

mediation_syntax <-"
    # Regressions
    # D ~ a_D*task_focus 
    # C ~ a_C*task_focus
    # d ~ a_d*task_focus
    # b ~ a_b*task_focus
    # a ~ a_a*task_focus
    p_us_id_or_val  ~ a_us_id_or_val*task_focus
    # ln_us_identity ~ a_us_identity*task_focus
    # I_valence_memory ~ a_inter*task_focus
    ec_effect ~ b_us_id_or_val*p_us_id_or_val + ade*task_focus
    
    #Define New Parameters
    # ab_us_valence := a_us_valence*b_us_valence
    ab_us_id_or_val := a_us_id_or_val*b_us_id_or_val
    # ab_inter := a_inter*b_inter
    total_effect := ade + ab_us_id_or_val #having defined ab, we can use this here.
"

path_model <- sem(mediation_syntax, data = data)
path_model |>
  summary(standardized=TRUE)

# m1 <- lm(ln_us_identity ~ task_focus, data = data) |>
#   plot()
# m2 <- lm(ln_us_valence ~ task_focus, data = data) |>
#   plot()
linear_model <- lm(ec_effect ~ task_focus * scale(p_us_id_or_val), data = data)
  # emtrends(var = "p_us_id_or_val", specs = ~ task_focus) |>
  # summary(infer = TRUE)
linear_model |>
  ggpredict(terms = ~ p_us_id_or_val + task_focus) |>
  plot(show_data = TRUE)

summary(linear_model)

```


