---
title : Experiment 3
author: Karoline Bading & Marius Barth
date  : "`r Sys.Date()`"
abstract: |
  *Beware, this is a test script!
  Keep in mind that (1) exclusion criteria are not applied and (2) only the test data are used.*

output:
  html_document:
    toc: yes
    toc_float: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---



```{r setup, include = FALSE}
library(afex)
library(emmeans)
library(papaja)
library(memoise)
library(HMMTreeC)

project_root <- rprojroot::find_rstudio_root_file()
study_folder <- file.path(project_root, "studies", "wsw3-main")

set_sum_contrasts()

knitr::opts_chunk$set(
  echo = TRUE
  , message = FALSE
)

source(file.path(project_root, "R", "mptinr_helper.R"))

file_cache <- cache_filesystem(path = file.path(rprojroot::find_rstudio_root_file(), ".rcache"), compress = "gzip")
simpleMPT <- memoise(TreeBUGS::simpleMPT, cache = file_cache)
BayesFactorMPT <- memoise(TreeBUGS::BayesFactorMPT, cache = file_cache)
```


```{r exp3-read-data}
mpt_data <- readRDS(file.path(study_folder, "data", "mpt_data.rds"))
rating <- readRDS(file.path(study_folder, "data", "rating.rds"))
```


## Evaluative rating

```{r}
table(rating$sid)
table(rating$us_valence)
table(rating$us_age)
table(rating$us_valence,rating$us_age)
table(rating$evaluative_rating)
```

```{r exp3-rating}
apa_beeplot(
  data = subset(rating, !is.na(us_valence))
  , id = "sid"
  , dv = "evaluative_rating"
  , factors = c("task_focus", "us_valence")
  , ylim = c(1, 8)
  , args_legend = list(x = "topleft")
)

anova_rating_model <- aov_4(
  formula = evaluative_rating ~ task_focus * (us_valence | sid)
  , data = subset(rating, !is.na(us_valence))
  , fun_aggregate = mean
)

marginal_means <- emmeans(
  anova_rating_model
  , specs = ~ us_valence + task_focus
) |>
  contrast(
    list(
      "EC effect, age-focus condition"       = c(1, -1, 0, 0)
      , "EC effect, valence-focus condition" = c(0, 0, 1, -1)
    )
    , side = ">"
  )

anova_rating <- apa_print(anova_rating_model)

rating_aggregated <- aggregate(evaluative_rating ~ us_valence + task_focus + sid, data = rating, FUN = mean)
rating_wide <- tidyr::pivot_wider(rating_aggregated, values_from = "evaluative_rating", names_from = "us_valence") |>
  within({
    ec_effect <- positive - negative
  })
marginal_means
```

main effect *task focus*,
`r anova_rating$full_result$task_focus`,
main effect *US valence*,
`r anova_rating$full_result$us_valence`,
two-way interaction *task focus* with *US valence*,
`r anova_rating$full_result$task_focus_us_valence`.

```{r eval = FALSE}
lme_model <- lmer(
  formula = evaluative_rating ~ us_valence * task_focus + (us_valence | sid) + (1 | cs)
  , data = subset(rating, !is.na(us_valence)) 
)
summary(lme_model)
ggeffects::ggpredict(lme_model, terms = ~ task_focus + us_valence) |>
  plot()
```


## MPT model

```{r}
table(recognition$sid)
table(recognition$us_valence,recognition$us_age)
table(recognition$reco_resp)
table(source$source_mem)
```


```{r exp3-ml-models}
baseline_restrictions <- list(
  G_x1 = .125
  , G_x2 = .125
)

hypothesis_restrictions <- list(
  baseline = list()
  , D_equal = list(D = c("D_x1", "D_x2"))
  , C_equal = list(C = c("C_x1", "C_x2"))
  , d_equal = list(d = c("d_x1", "d_x2"))
  , a_equal = list(a = c("a_x1", "a_x2"))
  , b_equal = list(b = c("b_x1", "b_x2"))
  # , Dage0   = list("D_x1=0")
  # , Dval0   = list("D_x2=0")
  # , Cage0   = list("C_x1=0")
  # , Cval0   = list("C_x2=0")
  # , dage0   = list("d_x1=0")
  # , dval0   = list("d_x2=0")
  # , bage5   = list("b_x1=0.5")
  # , bval5   = list("b_x2=0.5")
  # , aage5   = list("a_x1=0.5")
  # , aval5   = list("a_x2=0.5")
)

models <- lapply(
  hypothesis_restrictions
  , FUN = function(x) {
    fit_mpt(
      data = mpt_data
      , model = file.path(study_folder, "WSW_exp3.eqn")
      , restrictions = c(baseline_restrictions, x)
    )
  }
)
```

```{r exp3-compare-ml-models}
compare(models)
```

## Bayesian MPT model

```{r exp3-simple-mpt}
baseline_restrictions <- list(
  "G_x1 = G_x2 = .125"
)

simple_mpt <- lapply(
  hypothesis_restrictions
  , FUN = function(x) {
    # return(lapply(c(baseline_restrictions, x), FUN = paste, collapse = " = "))
    simpleMPT(
      eqnfile = file.path(study_folder, "WSW_exp3.eqn")
      , data = colSums(mpt_data)
      , restrictions = lapply(c(baseline_restrictions, x), FUN = paste, collapse = " = ")
      , n.iter   = 2e5L
      , n.burnin = 1e5L
      , n.thin   = 2e1L
      , ppp      = 5e3L
      , n.chains = 4e0L
      , cores    = 4e0L
    )
  }
)
BFs <- BayesFactorMPT(simple_mpt, cores = 4L)

# Compare baseline model with other models
data.frame(
  model = names(BFs$posterior[-1L])
  , logBF = log(BFs$posterior[-1L]) - log(BFs$posterior[[1L]])
  , row.names = NULL
) |> within({
  strong_evidence <- ifelse(abs(logBF) > log(10), "yes", "no")
  BF_01 <- exp( logBF)
  BF_10 <- exp(-logBF)
}) |>
  format(scientific = FALSE, digits = 4)

```
