---
title: "Test Script for who-said-what experiment 3"
author: "Karoline Bading"
output:
  html_document:
    toc: yes
    code_folding: show
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = NA)
```

# Load packages and read the data

```{r set}
#Load (or install and load) packages
require(pacman)
p_load('tidyverse', 'psych', 'effectsize', 'afex', 'bfrr', 'papaja', 'kableExtra', 'MPTinR', 'TreeBUGS','jsonlite') 
set_sum_contrasts()

project_root <- rprojroot::find_rstudio_root_file()
source(file.path(project_root, "R", "apa_print_treebugs.R"))
source(file.path(project_root, "R", "mptinr_helper.R"))

#setwd("~/Fuzzy-EC/Study 1/data and analyses")
read_file('data_pilot_study_raw.txt')%>%
#... split it into lines ...
 str_split('\n') %>% first() %>%
#... filter empty rows ...
 discard(function(x) x == '') %>%
#... parse JSON into a data.frame
 map_dfr(fromJSON, flatten=T) -> dat

length(unique(dat$url.srid))

dat$url.srid = as.factor(dat$url.srid)
dat$us_valence = as.factor(dat$us_valence)
dat$reco_resp = as.factor(dat$reco_resp)
```

```{r}
names(dat)
dat = dat %>%
   fill(url.srid, .direction = "down") %>% 
  group_by(url.srid) %>% 
  fill(consent, comment_study,pay_attention,serious,.direction = "down") %>%
  fill(consent, comment_study, pay_attention,serious, .direction = "up") %>% 
  select(url.srid, sender, consent, duration, ended_on, pay_attention, serious, response, response_action #general information
         ,comment_study,count_trial_learning, cs, us, us_valence,uss #learning phase
         , count_trial_memory, idtarg, reco_resp, source_mem  #memory phase
         , count_trial_ratings, cs_rating #rating phase 
         ) 

```

```{r exclude}
length(unique(dat$url.srid))
table(dat$pay_attention)
table(dat$serious)
table(dat$comment_study)
table(dat$sender)

dat <- subset(dat,pay_attention == 1 & serious == 1)
length(unique(dat$url.srid))
```

```{r}
ratings <- subset(dat,sender == "rating_trial")
table(ratings$cs_rating)
table(ratings$us_valence)
```

```{r}
ratings_cs <- subset(ratings,us_valence != "dist" & url.srid != 9908)
ratings_cs$cs_rating <- as.numeric(ratings_cs$cs_rating)
aov_ez(data=ratings_cs,id="url.srid",dv="cs_rating",within = c("us_valence"))
```

```{r}
apa_barplot(data=ratings_cs,id="url.srid",dv="cs_rating",factor = c("us_valence"))
```

```{r}
reco <- subset(dat,sender == "recognition_trial")
table(reco$reco_resp,reco$us_valence)
table(reco$us_valence)
```


```{r}
source <- subset(dat,sender == "source_trial")
#source <- merge(source,reco, by = c("url.srid","cs","us","us_valence","us_age","uss","idtarg","instructions_conditioning","sports"))
#source <- source[,c("url.srid","cs","us","us_valence","us_age","uss","idtarg","reco_resp.y","source_mem.x","instructions_conditioning","sports")]
#source_sub <- subset(source,reco_resp.y == "old")
#table(source_sub$source_mem.x)
#table(source_sub$us_valence)
#table(source_sub$us_valence,source_sub$us_age,source_sub$instructions_conditioning)
```

```{r}
learning <- subset(dat,sender == "learning_trial_cs_us_response")
table(learning$us_valence)
```

```{r}

reco <- reco[,c("url.srid","cs","us","us_valence","reco_resp")]
source <- source[,c("url.srid","cs","us","us_valence","uss","idtarg","source_mem")]
memory <- merge(reco,source,by=c("url.srid","cs","us","us_valence"))

```

```{r}
memory$correct_us_source <- NA
memory$source_mem_resp <- NA
for(i in 1:length(memory$url.srid)){
  memory$correct_us_source[i] <- memory$us[i]
  memory$source_mem_resp[i] <- memory$uss[[i]][as.numeric(substr(memory$source_mem, 3, 3))[i]]
}

memory$tree <- ifelse(memory$us_valence == "positive", "PosUS",ifelse(memory$us_valence == "negative","NegUS","New"))
memory$chosen_valence <- ifelse(memory$source_mem_resp%in%c("n6","n12","n9","n10","n5","n2","n1","n4","n8","n3","n7","n11"),"neg","pos")
memory$correct_US <- ifelse(memory$source_mem_resp==memory$correct_us_source,"cor","incor")

memory$mpt_resp <- ifelse(memory$reco_resp == "new",paste0(memory$tree,"new"),NA)
memory$mpt_resp <- ifelse(memory$reco_resp == "old",paste0(memory$tree,memory$chosen_valence,memory$correct_US),memory$mpt_resp)
```

```{r}
library(MPTinR)
MPTinR::check.mpt("WSW_pilot_hierarchical.eqn")

level_order <- check.mpt("WSW_pilot_hierarchical.eqn")$eqn.order.categories


memory$mpt_resp <- factor(memory$mpt_resp
                       , levels = level_order)

xxx <- table(memory$mpt_resp)
xxx2 <- data.frame(xxx)
mpt_dat <- data.frame(var1 = NA,
                      var2 = NA,
                      var3 = NA,
                      var4 = NA,
                      var5 = NA,
                      var6 = NA,
                      var7 = NA,
                      var8 = NA,
                      var9 = NA,
                      var10 = NA,
                      var11 = NA)

names(mpt_dat) <- level_order
mpt_dat[1,] <- xxx2$Freq
```

```{r}
mod_agg = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_pilot_hierarchical.eqn"
                  ,restrictions.filename = list("G=.25")
)

mod_agg_D0 = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_pilot_hierarchical.eqn"
                  ,restrictions.filename = list("G=.25",
                                                "D=0")
)

mod_agg_C0 = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_pilot_hierarchical.eqn"
                  ,restrictions.filename = list("G=.25",
                                                "C=0")
)

mod_agg_d0 = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_pilot_hierarchical.eqn"
                  ,restrictions.filename = list("G=.25",
                                                "d=0")
)

mod_agg_a5 = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_pilot_hierarchical.eqn"
                  ,restrictions.filename = list("G=.25",
                                                "a=.5")
)

mod_agg_b5 = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_pilot_hierarchical.eqn"
                  ,restrictions.filename = list("G=.25",
                                                "b=.5")
)


```

```{r}
model_comparisons <- anova(
  mod_agg
  , D0 = mod_agg_D0
  , C0 = mod_agg_C0
  , d0 = mod_agg_d0
  , a5 = mod_agg_a5
  , b5 = mod_agg_b5
)

dG2 <- apa_print(model_comparisons)
dG2
```

```{r}
mod_agg
```


```{r}
memory$correct_US_num <- ifelse(memory$correct_US=="cor",1,0)
memory$correct_valence <- ifelse(memory$us_valence == "positive" & memory$chosen_valence == "pos"|memory$us_valence == "negative" & memory$chosen_valence == "neg",1,0)

memoryCS <- subset(memory,us_valence!="dist")
memoryCS$correct_US_num2 <- 0
memoryCS$correct_valence2 <- 0
memoryCS$correct_US_num2 <- ifelse(memoryCS$reco_resp=="old",memoryCS$correct_US_num,memoryCS$correct_US_num2)
memoryCS$correct_valence2 <-ifelse(memoryCS$reco_resp=="old",memoryCS$correct_valence,memoryCS$correct_valence2)
```

```{r}
memory$mpt_resp2 <- ifelse(memory$reco_resp == "new",paste0(memory$tree,"new"),NA)
memory$mpt_resp2 <- ifelse(memory$reco_resp == "old",paste0(memory$tree,memory$chosen_valence,memory$correct_US),memory$mpt_resp2)

tmp <- table(memory$url.srid, memory$mpt_resp2)
mpt_data <- data.frame(
  NegUSnegcor = tmp[, "NegUSnegcor"]
)

for (i in colnames(tmp)) {
  mpt_data[[i]] <- tmp[, i]
}

mpt_data$url.srid <- rownames(mpt_data)

agg_data <- aggregate(cs_rating ~ us_valence + url.srid, data = ratings_cs, FUN = mean)
library(reshape2)
agg_data_d <- dcast(agg_data, value.var = "cs_rating", url.srid ~ us_valence)

agg_data_d$id <- rownames(agg_data_d)

mpt_data_c <- merge(mpt_data,agg_data_d, by = c("url.srid"))
```

```{r}
mpt_data_subset <- mpt_data_c

mpt_data <- mpt_data_subset[,2:12]

MPTinR::check.mpt("WSW_pilot_hierarchical.eqn")

if(file.exists("WSWpilot.rds")) {
  exp3pilot <- readRDS("WSWpilot.rds")
} else {

  WSWpilot = traitMPT(
  eqnfile = "WSW_pilot_hierarchical.eqn"
  , data = mpt_data
  , n.iter   = 4e4
  , n.adapt  =  2e3
  , n.burnin = 2e4
  , n.thin   = 4e1
  , n.chains = 4
  , restrictions = list("G=0.125")
  , ppp = 5e3
  , IVprec = "dgamma(.5,.5)"
  #, predType = c("f")
  )
  saveRDS(WSWpilot, file = "WSWpilot.rds")
}

#Fit the model and estimate parameters

summary(exp3pilot)
# 
TreeBUGS::plotFit(exp3pilot)
TreeBUGS::plotFreq(exp3pilot)
TreeBUGS::plotParam(exp3pilot)

# exp3pilot_ppp = PPP(exp3pilot, M = 5e3)
# exp3pilot_ppp

#MPT on aggregated frequencies
# mod_agg = fit.mpt(data = dat_mpt_freq_agg$n
#         ,model.filename = "KW_wsw_model.eqn"
#         ,restrictions.filename = list("Dn=Dpos=Dneg","G=0.25")
#         )
# mod_agg

individual_parameters <- as.data.frame(getParam(exp3pilot, parameter = "theta"))
parameter_names <- colnames(individual_parameters)
individual_parameters$id <- rownames(individual_parameters)
#saveRDS(individual_parameters, file = "individual-parameters-KB_both.rds")


para_ratings_both<- merge(mpt_data_c, individual_parameters, by = "id")
#save(para_ratings_both,file = "WSWpilot_x_ratings_val.rdata")
```

```{r}
cor.test(para_ratings_both$D,para_ratings_both$positive)
cor.test(para_ratings_both$D,para_ratings_both$negative)

cor.test(para_ratings_both$C,para_ratings_both$positive)
cor.test(para_ratings_both$C,para_ratings_both$negative)

cor.test(para_ratings_both$d,para_ratings_both$positive)
cor.test(para_ratings_both$d,para_ratings_both$negative)
```

```{r}
data <- para_ratings_both
data$ec <- data$positive - data$negative

library(lme4)
library(ggeffects)

#contrasts(data$instructions_conditioning) <- "contr.sum"                   # = effects coding (i.e. sum-to-zero contrasts)
cntr <- center <- function(x) { x - mean(x, na.rm = TRUE) } # = function for centering

model <- lm(
  formula = ec ~ cntr(D)+cntr(C)+cntr(d)+cntr(b)+cntr(a)
  , data = data
)
#car::scatterplotMatrix(data[, c("D", "C", "d")])

summary(model)
plot(model)
#ggpredict(model, terms = ~ D + instructions_conditioning) |>
  #plot(show_data = TRUE)

# emmeans(model) |> 
#   summary(infer = TRUE, side = ">")
```

```{r}
library(emmeans)
emtrends(model, specs = ~ 1, var = "D")

ggeffect(model, terms = ~ D) |>
  plot(rawdata = TRUE)
```

```{r}
ggeffect(model, terms = ~ cntr(C)) |>
  plot(rawdata = TRUE)
```

```{r}
ggeffect(model, terms = ~ cntr(d)) |>
  plot(rawdata = TRUE)
```

```{r}
rat <- merge(para_ratings_both,ratings_cs,by=c("url.srid"))
```

```{r}
rat$us_valence <- factor(rat$us_valence)
contrasts(rat$us_valence) <- "contr.sum"
model_1 <- lmer(formula = cs_rating ~ (cntr(D)+cntr(C)+cntr(d)+cntr(a)+cntr(b))*us_valence + (1|url.srid)
     , data = rat)

summary(model_1)
ggeffect(model_1, terms = ~ d:us_valence) |>
  plot(rawdata = TRUE)
ggeffect(model_1, terms = ~ C:us_valence) |>
  plot(rawdata = TRUE)

library(emmeans)
emtrends(model_1, specs = ~ us_valence, var = "d",infer=TRUE)
emtrends(model_1, specs = ~ us_valence, var = "C",infer=TRUE)
```

