---
title: "Test Script for who-said-what experiment 2"
author: "Karoline Bading"
output:
  html_document:
    toc: yes
    code_folding: show
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, comment = NA)
```

# Load packages and read the data

```{r set}
#Load (or install and load) packages
require(pacman)
p_load('tidyverse', 'psych', 'effectsize', 'afex', 'bfrr', 'papaja', 'kableExtra', 'MPTinR', 'TreeBUGS','jsonlite') 
set_sum_contrasts()

project_root <- rprojroot::find_rstudio_root_file()
source(file.path(project_root, "R", "apa_print_treebugs.R"))
source(file.path(project_root, "R", "mptinr_helper.R"))

setwd("~/Fuzzy-EC/Study 2/data and analyses")
# read_file('val_batch_final.txt')%>%
# #... split it into lines ...
#  str_split('\n') %>% first() %>%
# #... filter empty rows ...
#  discard(function(x) x == '') %>%
# #... parse JSON into a data.frame
#  map_dfr(fromJSON, flatten=T) -> dat
# 
# read_file('age_batch_final.txt')%>%
# #... split it into lines ...
#  str_split('\n') %>% first() %>%
# #... filter empty rows ...
#  discard(function(x) x == '') %>%
# #... parse JSON into a data.frame
#  map_dfr(fromJSON, flatten=T) -> dat2
# 
# dat <- rbind(dat,dat2)

dat <- readRDS("study2.RDS")

dat$url.srid = as.factor(dat$url.srid)
dat$us_valence = as.factor(dat$us_valence)
dat$reco_resp = as.factor(dat$reco_resp)
```

```{r}
# dat = dat %>%
#    fill(url.srid, .direction = "down") %>% 
#   group_by(url.srid) %>% 
#   fill(consent, comment_study,pay_attention,serious, instructions_conditioning, '-0','-1','-2','-3','-4','-5','-6','-7', .direction = "down") %>%
#   fill(consent, comment_study, pay_attention,serious,instructions_conditioning,'-0','-1','-2','-3','-4','-5','-6','-7', .direction = "up") %>% 
#   select(url.srid, sender, consent, duration, ended_on, pay_attention, serious, response, response_action #general information
#          , '-0','-1','-2','-3','-4','-5','-6','-7',comment_study,count_trial_learning, cs, us, us_valence, us_age, uss, resp_pos_learning #learning phase
#          , count_trial_memory, idtarg, reco_resp, source_mem  #memory phase
#          , count_trial_ratings, cs_rating #rating phase 
#          , instructions_conditioning #counterbalancing order in the test phase
#          ) 
# 
# dat$sports <- ifelse(dat$'-1'==TRUE|
#                        dat$'-2'==TRUE|
#                        dat$'-3'==TRUE|
#                        dat$'-4'==TRUE|
#                        dat$'-5'==TRUE|
#                        dat$'-0'==TRUE|
#                        dat$'-6'==TRUE|
#                        dat$'-7'==TRUE,0,1)
```

```{r exclude}
length(unique(dat$url.srid))
table(dat$pay_attention)
table(dat$serious)

length(unique(dat$url.srid))

```

```{r}
# ratings <- subset(dat,sender == "rating_trial")
# table(ratings$cs_rating)
# table(ratings$us_valence)
# table(ratings$us_valence,ratings$us_age,ratings$instructions_conditioning)
```

```{r}
ratings_cs <- subset(dat,us_valence != "dist")
ratings_cs$cs_rating <- as.numeric(ratings_cs$cs_rating)

aov_ez(data=ratings_cs,id="url.srid",dv="cs_rating",within = c("us_valence"),between = c("order"))
```

```{r}
apa_barplot(data=ratings_cs,id="url.srid",dv="cs_rating",factor = c("order","us_valence"))
```

```{r}
memfirst <- subset(ratings_cs,order == "mem_first")
aov_ez(data=memfirst,id="url.srid",dv="cs_rating",within = c("us_valence"))

evalfirst <- subset(ratings_cs,order == "eval_first")
aov_ez(data=evalfirst,id="url.srid",dv="cs_rating",within = c("us_valence"))

```


```{r}
# reco <- subset(dat,sender == "recognition_trial")
# table(reco$reco_resp,reco$us_valence)
# table(reco$us_valence)
# table(reco$us_valence,reco$us_age,reco$instructions_conditioning)
```


```{r}
#source <- subset(dat,sender == "source_trial")
#source <- merge(source,reco, by = c("url.srid","cs","us","us_valence","us_age","uss","idtarg","instructions_conditioning","sports"))
#source <- source[,c("url.srid","cs","us","us_valence","us_age","uss","idtarg","reco_resp.y","source_mem.x","instructions_conditioning","sports")]
#source_sub <- subset(source,reco_resp.y == "old")
#table(source_sub$source_mem.x)
#table(source_sub$us_valence)
#table(source_sub$us_valence,source_sub$us_age,source_sub$instructions_conditioning)
```

```{r}
# learning <- subset(dat,sender == "learning_trial_cs_us_response")
# table(learning$us_valence)
# table(learning$us_valence,learning$us_age)
# 
# learning$cs_sex <- ifelse(learning$cs %in% c("045_m_m_n_a","179_m_m_n_a","104_m_m_n_a","159_m_m_n_a","126_m_m_n_a","014_m_m_n_a","070_m_m_n_a","068_m_m_n_a","165_m_m_n_a","007_m_m_n_a","087_m_m_n_a","155_m_m_n_a","136_m_m_n_a","142_m_m_n_a","082_m_m_n_a","149_m_m_n_a","026_m_m_n_a","108_m_m_n_a","051_m_m_n_a","169_m_m_n_a","038_m_m_n_a","178_m_m_n_a","058_m_m_n_a","032_m_m_n_a"),"male","female")
# 
# table(learning$response,learning$us_age)
```

```{r}

# reco <- reco[,c("url.srid","instructions_conditioning","cs","us","us_valence","us_age","reco_resp")]
# source <- source[,c("url.srid","instructions_conditioning","cs","us","us_valence","us_age","uss","idtarg","source_mem")]
# memory <- merge(reco,source,by=c("url.srid","instructions_conditioning","cs","us","us_valence","us_age"))

memory <- dat
```

```{r}
memory$correct_us_source <- NA
memory$source_mem_resp <- NA
for(i in 1:length(memory$url.srid)){
  memory$correct_us_source[i] <- memory$us[i]
  memory$source_mem_resp[i] <- memory$uss[[i]][as.numeric(substr(memory$source_mem, 3, 3))[i]]
}

memory$tree <- ifelse(memory$us_valence == "positive", "PosUS",ifelse(memory$us_valence == "negative","NegUS","New"))
memory$chosen_valence <- ifelse(memory$source_mem_resp%in%c("n9","n10","n7","n5","n4","n2","n3","n8","n6","n1","n12","n11"),"neg","pos")
memory$correct_US <- ifelse(memory$source_mem_resp==memory$correct_us_source,"cor","incor")
memory$condition <- ifelse(memory$order=="eval_first","x1","x2")

memory$mpt_resp <- ifelse(memory$reco_resp == "new",paste0(memory$tree,"new_",memory$condition),NA)
memory$mpt_resp <- ifelse(memory$reco_resp == "old",paste0(memory$tree,memory$chosen_valence,memory$correct_US,"_",memory$condition),memory$mpt_resp)
```

```{r}
library(MPTinR)
MPTinR::check.mpt("WSW_exp2.eqn")

level_order <- check.mpt("WSW_exp2.eqn")$eqn.order.categories


memory$mpt_resp <- factor(memory$mpt_resp
                       , levels = level_order)

xxx <- table(memory$mpt_resp)
xxx2 <- data.frame(xxx)
mpt_dat <- data.frame(var1 = NA,
                      var2 = NA,
                      var3 = NA,
                      var4 = NA,
                      var5 = NA,
                      var6 = NA,
                      var7 = NA,
                      var8 = NA,
                      var9 = NA,
                      var10 = NA,
                      var11 = NA,
                      var12 = NA,
                      var13 = NA,
                      var14 = NA,
                      var15 = NA,
                      var16 = NA,
                      var17 = NA,
                      var18=NA,
                      var19=NA,
                      var20=NA,
                      var21=NA,
                      var22=NA)

names(mpt_dat) <- level_order
mpt_dat[1,] <- xxx2$Freq
```

```{r}
mod_agg = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25")
)

mod_agg

mod_agg_D = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25",
                                                "D_x1=D_x2")
)

mod_agg_C = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25",
                                                "C_x1=C_x2")
)

mod_agg_d = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25",
                                                "d_x1=d_x2")
)

mod_agg_a = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25",
                                                "a_x1=a_x2")
)

mod_agg_b = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25",
                                                "b_x1=b_x2")
)

mod_agg_dval0 = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25",
                                                "d_x2=0")
)

mod_agg_dage0 = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25",
                                                "d_x1=0")
)

mod_agg_Cage0 = fit.mpt(data = mpt_dat
                  ,model.filename = "WSW_exp2.eqn"
                  ,restrictions.filename = list("G_x1=.25","G_x2=.25",
                                                "C_x1=0")
)
```

```{r}
model_comparisons <- anova(
  mod_agg
  , Dageval = mod_agg_D
  , Cageval = mod_agg_C
  , dageval = mod_agg_d
  , aageval = mod_agg_a
  , bageval = mod_agg_b
  , Cage0 = mod_agg_Cage0
  , dage0 = mod_agg_dage0
  , dval0 = mod_agg_dval0
)

dG2 <- apa_print(model_comparisons)
dG2
```

```{r}
memory$correct_US_num <- ifelse(memory$correct_US=="cor",1,0)
memory$correct_valence <- ifelse(memory$us_valence == "positive" & memory$chosen_valence == "pos"|memory$us_valence == "negative" & memory$chosen_valence == "neg",1,0)


memoryCSold <- subset(memory,us_valence!="dist" & reco_resp == "old")
apa_barplot(memoryCSold,id="url.srid",dv="correct_US_num",factors=c("order"))
aov_ez(data=memoryCSold,id="url.srid",dv="correct_US_num",between=c("order"))
apa_barplot(memoryCSold,id="url.srid",dv="correct_valence",factors=c("order"))
aov_ez(data=memoryCSold,id="url.srid",dv="correct_valence",between=c("order"))

memoryCS <- subset(memory,us_valence!="dist")
memoryCS$correct_US_num2 <- 0
memoryCS$correct_valence2 <- 0
memoryCS$correct_US_num2 <- ifelse(memoryCS$reco_resp=="old",memoryCS$correct_US_num,memoryCS$correct_US_num2)
apa_barplot(memoryCS,id="url.srid",dv="correct_US_num2",factors=c("order"))
aov_ez(data=memoryCS,id="url.srid",dv="correct_US_num2",between=c("order"))
memoryCS$correct_valence2 <-ifelse(memoryCS$reco_resp=="old",memoryCS$correct_valence,memoryCS$correct_valence2)
apa_barplot(memoryCS,id="url.srid",dv="correct_valence2",factors=c("order"))
aov_ez(data=memoryCS,id="url.srid",dv="correct_valence2",between=c("order"))
```

```{r}
# names(learning)
# table(learning$response)
# table(learning$response,learning$us_valence)
# table(learning$response,learning$us_age)
# 
# table(learning$response,learning$cs_sex)
```

```{r}
memory$mpt_resp2 <- ifelse(memory$reco_resp == "new",paste0(memory$tree,"new"),NA)
memory$mpt_resp2 <- ifelse(memory$reco_resp == "old",paste0(memory$tree,memory$chosen_valence,memory$correct_US),memory$mpt_resp2)

tmp <- table(memory$url.srid, memory$mpt_resp2)
mpt_data <- data.frame(
  NegUSnegcor = tmp[, "NegUSnegcor"]
)

for (i in colnames(tmp)) {
  mpt_data[[i]] <- tmp[, i]
}

mpt_data$url.srid <- rownames(mpt_data)

data_mpt_condition <- subset(memory, us == "n9")
data_mpt_condition <- data_mpt_condition[,c("url.srid","order")]

mpt_data_b <- merge(mpt_data,data_mpt_condition, by = c("url.srid"))

agg_data <- aggregate(cs_rating ~ us_valence + url.srid + order, data = ratings_cs, FUN = mean)
library(reshape2)
agg_data_d <- dcast(agg_data, value.var = "cs_rating", url.srid + order ~ us_valence)

agg_data_d$id <- rownames(agg_data_d)

mpt_data_c <- merge(mpt_data_b,agg_data_d, by = c("url.srid","order"))
```

```{r}
mpt_data_subset <- mpt_data_c

cov_data <- mpt_data_subset[,c("url.srid","order")]
mpt_data <- mpt_data_subset[,3:13]

MPTinR::check.mpt("WSW_exp2_hierarchical.eqn")

if(file.exists("WSWexp2.rds")) {
  exp3pilot <- readRDS("WSWexp2.rds")
} else {

  WSWexp2 = traitMPT(
  eqnfile = "WSW_exp2_hierarchical.eqn"
  , data = mpt_data
  , n.iter   = 4e4
  , n.adapt  =  2e3
  , n.burnin = 2e4
  , n.thin   = 4e1
  , n.chains = 4
  , restrictions = list("G=0.125")
  , ppp = 5e3
  , covData=cov_data
  , predStructure=list("a; order","b; order","D; order",
                       "d; order","C; order"
                       )
  , IVprec = "dgamma(.5,.5)"
  #, predType = c("f")
  )
  saveRDS(WSWexp2, file = "WSWexp2.rds")
}

#Fit the model and estimate parameters

summary(WSWexp2)
# 
TreeBUGS::plotFit(WSWexp2)
TreeBUGS::plotFreq(WSWexp2)
TreeBUGS::plotParam(WSWexp2)

# exp3pilot_ppp = PPP(exp3pilot, M = 5e3)
# exp3pilot_ppp

#MPT on aggregated frequencies
# mod_agg = fit.mpt(data = dat_mpt_freq_agg$n
#         ,model.filename = "KW_wsw_model.eqn"
#         ,restrictions.filename = list("Dn=Dpos=Dneg","G=0.25")
#         )
# mod_agg

individual_parameters <- as.data.frame(getParam(WSWexp2, parameter = "theta"))
parameter_names <- colnames(individual_parameters)
individual_parameters$id <- rownames(individual_parameters)
#saveRDS(individual_parameters, file = "individual-parameters-KB_both.rds")


para_ratings_both<- merge(mpt_data_subset, individual_parameters, by = "id")
save(para_ratings_both,file = "WSWexp2_x_ratings_val.rdata")
```

```{r}
cor.test(para_ratings_both$D,para_ratings_both$positive)
cor.test(para_ratings_both$D,para_ratings_both$negative)

cor.test(para_ratings_both$C,para_ratings_both$positive)
cor.test(para_ratings_both$C,para_ratings_both$negative)

cor.test(para_ratings_both$d,para_ratings_both$positive)
cor.test(para_ratings_both$d,para_ratings_both$negative)
```

```{r}
data <- para_ratings_both
data$ec <- data$positive - data$negative
data$order <- factor(data$order, levels = c("eval_first","mem_first"))

library(lme4)
library(ggeffects)

contrasts(data$order) <- "contr.sum"                   # = effects coding (i.e. sum-to-zero contrasts)
cntr <- center <- function(x) { x - mean(x, na.rm = TRUE) } # = function for centering

model <- lm(
  formula = ec ~ (cntr(D) + cntr(C) + cntr(d) + cntr(a) + cntr(b))*order
  , data = data
)
#car::scatterplotMatrix(data[, c("D", "C", "d")])

summary(model)
plot(model)
#ggpredict(model, terms = ~ D + instructions_conditioning) |>
  #plot(show_data = TRUE)

library(emmeans)
emmeans(model, specs = ~ order) |> 
  summary(infer = TRUE, side = ">")
```

```{r}
library(emmeans)
emtrends(model, specs = ~ 1, var = "D")

ggeffect(model, terms = ~ D) |>
  plot(rawdata = TRUE)
```


```{r}
ggeffect(model, terms = ~ cntr(D) * instructions_conditioning) |>
  plot(rawdata = TRUE)
```

```{r}
ggeffect(model, terms = ~ cntr(C) * instructions_conditioning) |>
  plot(rawdata = TRUE)
```

```{r}
ggeffect(model, terms = ~ cntr(d) * instructions_conditioning) |>
  plot(rawdata = TRUE)
```

```{r}
ggeffect(model, terms = ~ cntr(d)) |>
  plot(rawdata = TRUE)
```

## Mediation

```{r}
library(mediation)
mediation_results <- mediate(
  model.m = lm(b ~ order, data = data)
  , model.y = lm(ec ~ b * order, data = data)
  , mediator = "b"
  , treat = "order"
  , treat.value = "mem_first"
  , control.value = "eval_first"
)
summary(mediation_results)
```


